const{net}=require("electron");const bootstrap=require("../data/players");const LEAGUES=[["lck","LCK"],["lec","LEC"],["lpl","LPL"],["lcs","LCS"],["lcp","LCP"]];
const laneOf=x=>String(x?.lane?.value??x?.lane??x?.position??x?.role??"").toUpperCase();const isMid=x=>["MID","MIDDLE","MIDLANE","MID LANER"].some(k=>laneOf(x).includes(k));
function rankOf(x){if(x?.rank&&typeof x.rank==="object")return x.rank;return(x?.ranks||[]).find(r=>r.queue==="RANKED_SOLO_5x5")||{}}
function points(r={}){const o={CHALLENGER:10,GRANDMASTER:9,MASTER:8,DIAMOND:7,EMERALD:6,PLATINUM:5,GOLD:4,SILVER:3,BRONZE:2,IRON:1};return(o[String(r.tier||"").toUpperCase()]||0)*100000+(Number(r.leaguePoints??r.lp)||0)}
async function getJson(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await net.fetch(url,{headers:{"User-Agent":"Mozilla/5.0 MidWatch/2.0","Accept":"application/json"},signal:c.signal});if(!r.ok)throw new Error(`Source SoloQ HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function mergeRows(rows,region){const m=new Map();for(const row of rows){if(!row||!isMid(row))continue;const name=String(row.displayName||row.proName||row.name||"").trim();if(!name)continue;const k=name.toLowerCase(),rank=rankOf(row);if(!m.has(k))m.set(k,{id:`pro-${region.toLowerCase()}-${k.replace(/[^a-z0-9]+/g,"-")}`,name,team:String(row.team||""),region,platform:String(row.platform||"").toUpperCase(),role:"MID",source:"live",accounts:[],live:false,bestRank:{}});const p=m.get(k);if(row.team)p.team=String(row.team);if(row.platform)p.platform=String(row.platform).toUpperCase();p.live=p.live||Boolean(row.isLive);const a={gameName:String(row.gameName||""),tagLine:String(row.tagLine||""),puuid:String(row.puuid||rank.puuid||""),platform:String(row.platform||rank.platform||"").toUpperCase(),rank,isLive:Boolean(row.isLive),profileIcon:row.profileIcon||null};if(a.gameName&&a.tagLine&&!p.accounts.some(x=>x.gameName.toLowerCase()===a.gameName.toLowerCase()&&x.tagLine.toLowerCase()===a.tagLine.toLowerCase()))p.accounts.push(a);if(points(rank)>points(p.bestRank))p.bestRank=rank}return[...m.values()].sort((a,b)=>a.team.localeCompare(b.team)||a.name.localeCompare(b.name))}
async function refreshPros(){const all=[],errors=[];for(const[code,label]of LEAGUES){try{const d=await getJson(`https://dpm.lol/v1/esport/soloq/leagues/${code}/leaderboard`),rows=Array.isArray(d)?d:(Array.isArray(d?.players)?d.players:[]),mids=mergeRows(rows,label);if(!mids.length)throw new Error("aucun midlaner reçu");all.push(...mids)}catch(e){errors.push(`${label}: ${e.message}`);all.push(...bootstrap.filter(p=>p.region===label))}}const seen=new Set();return{players:all.filter(p=>{const k=`${p.region}|${p.name}`.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}),errors}}
async function profile(name){try{return await getJson(`https://dpm.lol/v1/pros/${encodeURIComponent(name)}`)}catch(_){return null}}
module.exports={refreshPros,profile};
