const{net}=require("electron");const bootstrap=require("../data/players");
const LEAGUES=[["lck","LCK"],["lckcl","LCKCL"],["lec","LEC"],["lfl","LFL"],["lpl","LPL"],["lcs","LCS"],["lcp","LCP"]];
const laneOf=x=>String(x?.lane?.value??x?.lane??x?.position??x?.role??"").toUpperCase();
const isMid=x=>["MID","MIDDLE","MIDLANE","MID LANER"].some(k=>laneOf(x).includes(k));
function rankOf(x){if(x?.rank&&typeof x.rank==="object")return x.rank;return(x?.ranks||[]).find(r=>r.queue==="RANKED_SOLO_5x5"||r.queueType==="RANKED_SOLO_5x5")||{}}
function points(r={}){const o={CHALLENGER:10,GRANDMASTER:9,MASTER:8,DIAMOND:7,EMERALD:6,PLATINUM:5,GOLD:4,SILVER:3,BRONZE:2,IRON:1};return(o[String(r.tier||"").toUpperCase()]||0)*100000+(Number(r.leaguePoints??r.lp)||0)}
async function getJson(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await net.fetch(url,{headers:{"User-Agent":"Mozilla/5.0 MidPulse/3.1","Accept":"application/json"},signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function mergeRows(rows,region){const m=new Map();for(const row of rows){if(!row||!isMid(row))continue;const name=String(row.displayName||row.proName||row.name||"").trim();if(!name)continue;const k=name.toLowerCase(),rank=rankOf(row);if(!m.has(k))m.set(k,{id:`pro-${region.toLowerCase()}-${k.replace(/[^a-z0-9]+/g,"-")}`,name,team:String(row.team?.name||row.team||""),region,platform:String(row.platform||"").toUpperCase(),role:"MID",source:"DPM public data",accounts:[],live:false,bestRank:{}});const p=m.get(k);if(row.team)p.team=String(row.team?.name||row.team);if(row.platform)p.platform=String(row.platform).toUpperCase();p.live=p.live||Boolean(row.isLive||row.live||row.inGame);const a={gameName:String(row.gameName||row.riotId?.gameName||""),tagLine:String(row.tagLine||row.riotId?.tagLine||""),puuid:String(row.puuid||rank.puuid||""),platform:String(row.platform||rank.platform||"").toUpperCase(),rank,isLive:Boolean(row.isLive||row.live||row.inGame),profileIcon:row.profileIcon||null};if(a.gameName&&a.tagLine&&!p.accounts.some(x=>x.gameName.toLowerCase()===a.gameName.toLowerCase()&&x.tagLine.toLowerCase()===a.tagLine.toLowerCase()))p.accounts.push(a);if(points(rank)>points(p.bestRank))p.bestRank=rank}return[...m.values()].sort((a,b)=>a.team.localeCompare(b.team)||a.name.localeCompare(b.name))}
async function league(code,label){const urls=[`https://dpm.lol/v1/esport/soloq/leagues/${code}/leaderboard`,`https://dpm.lol/api/esport/soloq/leagues/${code}/leaderboard`];let last;for(const url of urls){try{const d=await getJson(url),rows=Array.isArray(d)?d:Array.isArray(d?.players)?d.players:Array.isArray(d?.data)?d.data:[],mids=mergeRows(rows,label);if(mids.length)return{players:mids,error:""}}catch(e){last=e}}return{players:bootstrap.filter(p=>p.region===label),error:`${label}: ${last?.message||"source indisponible"}`}}
async function refreshPros(){const results=await Promise.all(LEAGUES.map(([c,l])=>league(c,l))),all=results.flatMap(x=>x.players),errors=results.map(x=>x.error).filter(Boolean),seen=new Set();return{players:all.filter(p=>{const k=`${p.region}|${p.name}`.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}),errors}}
async function profile(name){for(const url of [`https://dpm.lol/v1/pros/${encodeURIComponent(name)}`,`https://dpm.lol/api/pros/${encodeURIComponent(name)}`])try{return await getJson(url)}catch(_){}return null}
module.exports={refreshPros,profile};
