const fs=require("fs"),path=require("path"),{spawn}=require("child_process");
const HOSTS={BR1:"spectator.br1.lol.riotgames.com:80",EUN1:"spectator.eun1.lol.riotgames.com:80",EUW1:"spectator.euw1.lol.riotgames.com:80",JP1:"spectator.jp1.lol.riotgames.com:80",KR:"spectator.kr.lol.riotgames.com:80",LA1:"spectator.la1.lol.riotgames.com:80",LA2:"spectator.la2.lol.riotgames.com:80",NA1:"spectator.na1.lol.riotgames.com:80",OC1:"spectator.oc1.lol.riotgames.com:80",TR1:"spectator.tr1.lol.riotgames.com:80",RU:"spectator.ru.lol.riotgames.com:80",SG2:"spectator.sg2.lol.pvp.net:8080",TW2:"spectator.tw2.lol.pvp.net:8080",VN2:"spectator.vn2.lol.pvp.net:8080",PH2:"spectator.ph2.lol.pvp.net:8080",TH2:"spectator.th2.lol.pvp.net:8080"};
const valid=r=>r&&fs.existsSync(path.join(r,"Game","League of Legends.exe"));
function detect(saved=""){const drives=["C","D","E","F","G"],c=[saved,...drives.flatMap(d=>[`${d}:\\Riot Games\\League of Legends`,`${d}:\\Games\\Riot Games\\League of Legends`]),"C:\\Program Files\\Riot Games\\League of Legends"];return c.find(valid)||""}
function args(root,game,locale){const p=String(game?.platformId||"").toUpperCase(),k=String(game?.observers?.encryptionKey||""),id=String(game?.gameId||"");if(!p||!k||!id)throw new Error("Données spectateur Riot incomplètes.");const host=HOSTS[p]||`spectator.${p.toLowerCase()}.lol.pvp.net:8080`;return{p,a:[`spectator ${host} ${k} ${id} ${p}`,`-GameBaseDir=${root}`,`-Locale=${locale}`]}}
function launch(root,game,locale="fr_FR"){root=detect(root);if(!root)throw new Error("Installation de League of Legends introuvable. Choisis son dossier dans Réglages.");const exe=path.join(root,"Game","League of Legends.exe"),x=args(root,game,locale);
  try{const child=spawn(exe,x.a,{cwd:path.dirname(exe),detached:true,stdio:"ignore",windowsHide:false});child.once("error",()=>{});child.unref();return root}
  catch(e){if(e.code!=="EPERM"&&e.code!=="EACCES")throw e}
  try{const psArgs=["-NoProfile","-NonInteractive","-WindowStyle","Hidden","-Command",`Start-Process -FilePath '${exe.replace(/'/g,"''")}' -WorkingDirectory '${path.dirname(exe).replace(/'/g,"''")}' -ArgumentList @('${x.a.map(v=>v.replace(/'/g,"''")).join("','")}')`];const child=spawn("powershell.exe",psArgs,{detached:true,stdio:"ignore",windowsHide:true});child.once("error",()=>{});child.unref();return root}
  catch(e){throw new Error("Windows bloque le lancement du spectateur League (EPERM). Lance MidPulse une fois en administrateur ou re-sélectionne le dossier League dans Réglages.")}
}
module.exports={detect,launch};