const fs=require("fs"),path=require("path"),https=require("https");
const valid=r=>r&&fs.existsSync(path.join(r,"Game","League of Legends.exe"));
function detect(saved=""){const drives=["C","D","E","F","G"],c=[saved,...drives.flatMap(d=>[`${d}:\\Riot Games\\League of Legends`,`${d}:\\Games\\Riot Games\\League of Legends`]),"C:\\Program Files\\Riot Games\\League of Legends"];return c.find(valid)||""}
function lcu(root){const file=path.join(root,"lockfile");if(!fs.existsSync(file))throw new Error("Ouvre d’abord le client League of Legends et connecte-toi, puis réessaie.");const raw=fs.readFileSync(file,"utf8").trim().split(":");if(raw.length<5)throw new Error("Lockfile League invalide.");return{port:+raw[2],password:raw[3],protocol:raw[4]||"https"}}
function request(root,endpoint,body){return new Promise((resolve,reject)=>{let a;try{a=lcu(root)}catch(e){return reject(e)}const data=JSON.stringify(body);const req=https.request({hostname:"127.0.0.1",port:a.port,path:endpoint,method:"POST",rejectUnauthorized:false,headers:{Authorization:"Basic "+Buffer.from("riot:"+a.password).toString("base64"),"Content-Type":"application/json","Content-Length":Buffer.byteLength(data)}},res=>{let out="";res.on("data",d=>out+=d);res.on("end",()=>{if(res.statusCode>=200&&res.statusCode<300)return resolve(out);let msg=out;try{const j=JSON.parse(out);msg=j.message||j.errorCode||out}catch(_){}reject(new Error(`Le client League a refusé le spectate (HTTP ${res.statusCode})${msg?": "+msg:""}`))})});req.on("error",e=>reject(new Error("Impossible de communiquer avec le client League : "+e.message)));req.write(data);req.end()})}
async function launch(root,game,puuid){root=detect(root);if(!root)throw new Error("Installation de League of Legends introuvable. Choisis son dossier dans Réglages.");const id=String(game?.gameId||""),key=String(game?.observers?.encryptionKey||"");if(!id||!key||!puuid)throw new Error("Données spectateur Riot incomplètes.");
 const body={dropInSpectateGameId:id,gameQueueType:String(game?.gameQueueConfigId||""),allowObserveMode:"ALL",puuid:String(puuid),spectatorKey:key};
 try{await request(root,"/lol-gameflow/v2/spectate/launch",body);return{root,verified:true,method:"LCU"}}catch(e1){
   try{await request(root,"/lol-spectator/v1/spectate/launch",body);return{root,verified:true,method:"LCU"}}catch(e2){throw new Error(e2.message+" (MidPulse passe maintenant par le client Riot/League, pas par le lancement direct bloqué par Vanguard.)")}
 }
}
module.exports={detect,launch};