const{app,BrowserWindow,ipcMain,shell,dialog}=require("electron");const path=require("path");const store=require("./store"),bootstrap=require("./data/players"),{Riot}=require("./services/riot"),pros=require("./services/pros"),spectate=require("./services/spectate"),ouat=require("./services/ouat");let mainWindow;
function currentPros(){const c=store.get("proCache",[]);return Array.isArray(c)&&c.length?c:bootstrap}function key(){return String(store.get("riotKey","")||"").trim()}
function create(){store.init();const found=spectate.detect(store.get("leaguePath",""));if(found&&found!==store.get("leaguePath",""))store.set("leaguePath",found);mainWindow=new BrowserWindow({width:1460,height:920,minWidth:1040,minHeight:700,show:false,backgroundColor:"#070a0f",title:"MidWatch",autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:false}});mainWindow.loadFile(path.join(__dirname,"renderer/index.html"));mainWindow.once("ready-to-show",()=>mainWindow.show())}
function data(){const o=store.get("ouat",{});return{players:currentPros(),ouatPlayers:o.players||[],ouat:{url:o.url||"",season:o.season||"",status:o.status||"",start:o.start||"",end:o.end||"",teams:o.teams||0,warning:o.warning||"",updatedAt:o.updatedAt||0},favorites:store.get("favorites",[]),hasKey:!!key(),leaguePath:spectate.detect(store.get("leaguePath","")),proCacheAt:store.get("proCacheAt",0)}}
ipcMain.handle("app:data",()=>data());
ipcMain.handle("favorite:toggle",(_e,id)=>{let f=store.get("favorites",[]);f=f.includes(id)?f.filter(x=>x!==id):[...f,id];store.set("favorites",f);return f});
ipcMain.handle("settings:key",(_e,v)=>{store.set("riotKey",String(v||"").trim());return!!key()});
ipcMain.handle("settings:pickLeague",async()=>{const r=await dialog.showOpenDialog(mainWindow,{title:"Choisis le dossier League of Legends",properties:["openDirectory"]});if(r.canceled||!r.filePaths[0])return store.get("leaguePath","");let root=r.filePaths[0];if(path.basename(root).toLowerCase()==="game")root=path.dirname(root);if(!spectate.detect(root))throw new Error("Ce dossier ne contient pas Game\\League of Legends.exe");store.set("leaguePath",root);return root});
ipcMain.handle("pros:refresh",async()=>{const r=await pros.refreshPros();if(r.players.length){store.set("proCache",r.players);store.set("proCacheAt",Date.now())}return{...r,at:Date.now()}});
ipcMain.handle("pros:profile",(_e,name)=>pros.profile(name));
ipcMain.handle("ouat:refresh",async(_e,url)=>{const r=await ouat.refresh(String(url||store.get("ouat",{}).url||""));store.set("ouat",r);return r});
ipcMain.handle("ouat:url",(_e,url)=>{const o=store.get("ouat",{});o.url=String(url||"").trim();store.set("ouat",o);return o.url});
ipcMain.handle("riot:check",async(_e,a)=>{if(!key())throw new Error("Ajoute ta clé Riot dans Settings.");const riot=new Riot(key()),acc=await riot.resolveAccount(a);let ranked=[];try{ranked=await riot.ranked(acc.platform,acc.puuid)}catch(_){}let active=null;try{active=await riot.active(acc.platform,acc.puuid)}catch(e){if(e.status!==404)throw e}return{account:acc,ranked,active}});
ipcMain.handle("spectate:launch",async(_e,a)=>{if(!key())throw new Error("Ajoute ta clé Riot dans Settings.");const riot=new Riot(key()),acc=await riot.resolveAccount(a);let game;try{game=await riot.active(acc.platform,acc.puuid)}catch(e){if(e.status===404)throw new Error("Ce joueur n’est plus en partie.");throw e}const root=spectate.launch(store.get("leaguePath",""),game);store.set("leaguePath",root);return{ok:true,gameId:game.gameId}});
ipcMain.handle("external:open",(_e,url)=>{if(/^https?:\/\//i.test(String(url)))return shell.openExternal(String(url));return false});
app.whenReady().then(create);app.on("activate",()=>BrowserWindow.getAllWindows().length===0&&create());app.on("window-all-closed",()=>process.platform!=="darwin"&&app.quit());
